# .github/workflows/sync-installer.yml
name: Sync Welcome Installer

on:
  push:
    branches: [main]
    paths:
      - 'templates/**'
      - '.github/workflows/sync-installer.yml'

jobs:
  update-installer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auto-update install_welcome.sh
        run: |
          echo "Replacing script hash placeholder with empty string (no longer needed)..."
          sed -i 's/^SCRIPT_HASH=.*//g' install_welcome.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git commit -am "Automated: Remove SCRIPT_HASH from installer"
          git push
        continue-on-error: true
