name: Sync SCRIPT_HASH in install_welcome.sh

on:
  push:
    paths:
      - 'install_welcome.sh'
      - 'templates/welcome.sh.template.en'

jobs:
  update-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Calculate SHA256 hash of English template
        id: calc_hash
        run: |
          NEW_HASH=$(sha256sum templates/welcome.sh.template.en | cut -c1-16)
          echo "new_hash=$NEW_HASH" >> $GITHUB_OUTPUT

      - name: Update SCRIPT_HASH in install_welcome.sh
        run: |
          sed -i "s/^SCRIPT_HASH=\"[a-f0-9]\{16\}\"/SCRIPT_HASH=\"${{ steps.calc_hash.outputs.new_hash }}\"/" install_welcome.sh

      - name: Check for changes in install_welcome.sh
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes if hash updated
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add install_welcome.sh
          git commit -m "chore: sync SCRIPT_HASH with template.en"
          git push
